---
require:
  - standard
  - rubocop-rails

inherit_gem:
  # Since we'll be invoking 'rubocop' directly, we need to include the standardrb config.
  standard: config/base.yml
  rubocop-rails: config/default.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - "Gemfile.lock"
    - "bin/*"
    - "config.ru"
  SuggestExtensions: false

#
# Override standardrb rules:
#

Lint/InterpolationCheck:
  Exclude:
    - "db/seeds.rb"

Lint/NumberConversion:
  # This seems to be pointless, and possibly harmless when we call #to_i just to make sure it's not a string.
  Enabled: no

Style/LambdaCall:
  Exclude:
    # jbuilder will be going away eventually. But for now, it has some long blocks.
    - "**/*.jbuilder"

Style/Semicolon:
  Exclude:
    # Semicolons are quite useful in specs and avoiding them results in much more convoluted code.
    - "spec/**/*.rb"

Style/FrozenStringLiteralComment:
  # https://github.com/rubocop-hq/rubocop/issues/7197 https://github.com/testdouble/standard/pull/181
  Enabled: yes

Style/StringLiterals:
  # Why should anyone care what kinds of quotes are used? Use what you use.
  Enabled: no

Style/StringLiteralsInInterpolation:
  # Why should anyone care what kinds of quotes are used? Use what you use.
  Enabled: no

Style/TrailingCommaInArguments:
  # Trailing commas on lists are the cleanest, easiest, least ambiguous way.
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  # Trailing commas on lists are the cleanest, easiest, least ambiguous way.
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  # Trailing commas on lists are the cleanest, easiest, least ambiguous way.
  EnforcedStyleForMultiline: comma

Bundler/GemComment:
  Enabled: true
  OnlyFor:
    - limiting_version_specifiers
    - github
    - git
    - path

#
# Add Rails cops, which standardrb doesn't enable.
#

Rails:
  Enabled: true

Rails/ActiveRecordCallbacksOrder: # (new in 2.7)
  Enabled: true
Rails/AddColumnIndex: # (new in 2.11)
  Enabled: true
Rails/AfterCommitOverride: # (new in 2.8)
  Enabled: true
Rails/AttributeDefaultBlockValue: # (new in 2.9)
  Enabled: true
Rails/EagerEvaluationLogMessage: # (new in 2.11)
  Enabled: true
Rails/EnvironmentVariableAccess: # (new in 2.10)
  Enabled: true
Rails/ExpandedDateRange: # (new in 2.11)
  Enabled: true
Rails/FindById: # (new in 2.7)
  Enabled: true
Rails/I18nLocaleAssignment: # (new in 2.11)
  Enabled: true
Rails/Inquiry: # (new in 2.7)
  Enabled: true
Rails/MailerName: # (new in 2.7)
  Enabled: true
Rails/MatchRoute: # (new in 2.7)
  Enabled: true
Rails/NegateInclude: # (new in 2.7)
  Enabled: true
Rails/Pluck: # (new in 2.7)
  Enabled: true
Rails/PluckInWhere: # (new in 2.7)
  Enabled: true
Rails/RenderInline: # (new in 2.7)
  Enabled: true
Rails/RenderPlainText: # (new in 2.7)
  Enabled: true
Rails/ShortI18n: # (new in 2.7)
  Enabled: true
Rails/SquishedSQLHeredocs: # (new in 2.8)
  Enabled: false # https://github.com/rubocop-hq/rubocop-rails/issues/365
Rails/TimeZoneAssignment: # (new in 2.10)
  Enabled: true
Rails/UnusedIgnoredColumns: # (new in 2.11)
  Enabled: true
Rails/WhereEquals: # (new in 2.9)
  Enabled: true
Rails/WhereExists: # (new in 2.7)
  Enabled: true
Rails/WhereNot: # (new in 2.8)
  Enabled: true
