#
# For more information see https://github.com/bbatsov/rubocop/blob/master/config/default.yml
#
# However, do not include entire blocks here just because you want to change them.
# Include only the specific lines that you're changing from the defaults.
#
---
require: rubocop-rspec
AllCops:
  Exclude:
  - "Gemfile.lock"
  - "db/schema.rb"
  - "tmp/**/*"
  - "config.ru"
  DisplayCopNames: true
  DisplayStyleGuide: true
  StyleGuideCopsOnly: false
Rails:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false
Metrics/LineLength:
  Max: 120
  Exclude:
  - 'db/**/*.rb'
Metrics/MethodLength:
  Exclude:
  - 'db/**/*.rb'
Metrics/BlockLength:
  Exclude:
  - 'Guardfile'
  - 'spec/**/*.rb'
  - 'app/controllers/api/**/*.rb'
  - 'app/admin/**/*.rb'
  - 'app/views/**/*.arb'
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/IndentArray:
  EnforcedStyle: consistent
Layout/IndentHash:
  EnforcedStyle: consistent
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Lint/AmbiguousBlockAssociation:
  Exclude:
  - 'spec/**/*.rb'
Style/BracesAroundHashParameters:
  Enabled: false
Style/BlockDelimiters:
  EnforcedStyle: semantic
  Exclude:
  - 'spec/factories/**/*.rb'
Style/ClassCheck:
  Enabled: false
Style/Documentation:
  Exclude:
  - 'db/**/*.rb'
Style/LambdaCall:
  Exclude:
  - '**/*.jbuilder'
Style/NumericLiterals:
  Exclude:
  - 'spec/**/*.rb'
Style/RegexpLiteral:
  Exclude:
  - 'Guardfile'
Style/StringLiterals:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
RSpec/ContextWording:
  Enabled: false
RSpec/EmptyLineAfterHook:
  Enabled: false
RSpec/EmptyLineAfterSubject:
  Enabled: false
RSpec/ExampleLength:
  Max: 10
RSpec/ImplicitSubject:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 5
RSpec/NestedGroups:
  Max: 6
RSpec/ScatteredLet:
  Enabled: false
RSpec/ScatteredSetup:
  Enabled: false
