#!/bin/bash
set -euo pipefail

if [[ $CIRCLE_REPOSITORY_URL =~ git@github.com:(.+)\.git ]]; then
  CIRCLE_REPOSITORY_URL="https://github.com/${BASH_REMATCH[1]}"
fi

payload=$(
cat <<EOM
{
    "attachments": [
        {
            "fallback": "$CIRCLE_PROJECT_REPONAME $CIRCLE_BRANCH branch build failed $CIRCLE_BUILD_URL",
            "color": "#ddaa00",
            "title": "$CIRCLE_PROJECT_REPONAME $CIRCLE_BRANCH Build Failure",
            "fields": [
                {"title": "Branch", "short": true, "value": "<$CIRCLE_REPOSITORY_URL/commit/$CIRCLE_SHA1|$CIRCLE_BRANCH at ${CIRCLE_SHA1:(-8)}>"},
                {"title": "Build", "short": true, "value": "<$CIRCLE_BUILD_URL|$CIRCLE_BUILD_NUM>"},
                {"title": "Committer", "short": true, "value": "<https://github.com/$CIRCLE_USERNAME|$CIRCLE_USERNAME>"},
            ]
        }
    ]
}
EOM
)
curl -X POST --data-urlencode payload="$payload" "$SLACK_WEBHOOK_URL"
