#!/bin/bash
set -euo pipefail

if [[ $CIRCLE_REPOSITORY_URL =~ git@github.com:(.+)\.git ]]; then
  CIRCLE_REPOSITORY_URL="https://github.com/${BASH_REMATCH[1]}"
fi
DEPLOYMENT_DESTINATION_NAME=$1

payload=$(
cat <<EOM
{
    "attachments": [
        {
            "fallback": "$CIRCLE_PROJECT_REPONAME deployment of $CIRCLE_BRANCH to $DEPLOYMENT_DESTINATION_NAME failed $CIRCLE_BUILD_URL",
            "color": "#ddaa00",
            "title": "$CIRCLE_PROJECT_REPONAME $CIRCLE_BRANCH deployment to $DEPLOYMENT_DESTINATION_NAME failed",
            "fields": [
                {"title": "Destination", "short": true, "value": "$DEPLOYMENT_DESTINATION_NAME"},
                {"title": "Branch", "short": true, "value": "<$CIRCLE_REPOSITORY_URL/commit/$CIRCLE_SHA1|$CIRCLE_BRANCH at ${CIRCLE_SHA1:(-8)}>"},
                {"title": "CircleCI Build", "short": true, "value": "<$CIRCLE_BUILD_URL|$CIRCLE_BUILD_NUM>"},
            ]
        }
    ]
}
EOM
)
curl -X POST --data-urlencode payload="$payload" "$SLACK_WEBHOOK_URL"
